const Data = [
    {
        id:1,
        category:"education",
        icon: 'icon-graduation',
        year: '2022 - present',
        title:'Bootcamp Full Stack Mern & Mobile Apps',
        desc: 'Accenture with Mindhub',
    },
    {
        id:2,
        category:"education",
        icon: 'icon-graduation',
        year: '2023',
        title:'Rosetta Stone',
        desc: 'Accenture App lenguaje',
    },
    {
        id:3,
        category:"education",
        icon: 'icon-graduation',
        year: '2023',
        title:'Agile methodologies',
        desc: 'Farmacity',
    },
    {
        id:4,
        category:"education",
        icon: 'icon-graduation',
        year: '2022',
        title:' Introduction to programming',
        desc: 'Foundation Mediapila with Plataforma 5',
    },
    {
        id:5,
        category:"education",
        icon: 'icon-graduation',
        year: '2022',
        title:'Cybersecurity and UX design',
        desc: 'Academia BA',
    },
    {
        id:6,
        category:"education",
        icon: 'icon-graduation',
        year: '2020 - 2021',
        title:'Full Stack Developer',
        desc: 'UTN',
    },
    {
        id:7,
        category:"experience",
        icon: 'icon-briefcase',
        year: '2020 - 2021',
        title:'Administración de consorcios Marcelo Osvaldo Vilar',
        desc: 'Building Manager: Control of the correct operation of facilities, maintenance and services',
    },
    {
        id:8,
        category:"experience",
        icon: 'icon-briefcase',
        year: '2019',
        title:'Child and elderly care',
        desc: 'Child and elderly care',
    },
    {
        id:9,
        category:"experience",
        icon: 'icon-briefcase',
        year: '2018',
        title:'Luis pesca',
        desc: 'Customer service and cashiering',
    },
    {
        id:10,
        category:"experience",
        icon: 'icon-briefcase',
        year: '2015',
        title:'Burger King',
        desc: 'Maintenance services: cleaning, organization, manufacturing supervision, customer service and cashiering',
    },

];

export default Data;